files:
  - source: /blog/a-clever-device-to-photograph-tins.html
    translation: /blog/%locale%/a-clever-device-to-photograph-tins.html

  - source: /blog/discover-the-5 colors-A-B-C-D-E-nutrition-grade-of-X-country-products-on-openfoodfacts.html
    translation: /blog/%locale%/discover-the-5 colors-A-B-C-D-E-nutrition-grade-of-X-country-products-on-openfoodfacts.html

  - source: /blog/graphs-in-3-clicks.html
    translation: /blog/%locale%/graphs-in-3-clicks.html
    
  - source: /blog/introducing-open-products-facts-all-your-product-are-belong-to-us.html
    translation: /blog/%locale%/introducing-open-products-facts-all-your-product-are-belong-to-us.html
    
  - source: /blog/launch-of-open-food-facts-join-the-food-revolution.html
    translation: /blog/%locale%/launch-of-open-food-facts-join-the-food-revolution.html
    
  - source: /blog/made-near-eu-and-makes-you-curious.html
    translation: /blog/%locale%/made-near-eu-and-makes-you-curious.html
    
  - source: /blog/open-and-linked-data-rdf-export-of-data.html
    translation: /blog/%locale%/open-and-linked-data-rdf-export-of-data.html
    
  - source: /blog/scanning-is-already-contributing.html
    translation: /blog/%locale%/scanning-is-already-contributing.html
    
  - source: /blog/support-open-food-facts-on-helloasso-and-lilo-and-be-a-part-the-hosting-of-the-project.html
    translation: /blog/%locale%/support-open-food-facts-on-helloasso-and-lilo-and-be-a-part-the-hosting-of-the-project.html
    
  - source: /blog/how-many-different-food-products-are-there-in-the-world.html
    translation: /blog/%locale%/how-many-different-food-products-are-there-in-the-world.html
